export default {
    SEND_NEW_MESSAGE_REQUEST: 'SEND_NEW_MESSAGE_REQUEST',
    SEND_NEW_MESSAGE_SUCCESS: 'SEND_NEW_MESSAGE_SUCCESS',
    SEND_NEW_MESSAGE_ERROR: 'SEND_NEW_MESSAGE_ERROR',
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
    REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
    GET_USER_CHATS_REQUEST: 'GET_USER_CHATS_REQUEST',
    GET_USER_CHATS_SUCCESS: 'GET_USER_CHATS_SUCCESS',
    GET_USER_CHATS_ERROR: 'GET_USER_CHATS_ERROR'
}